--
-- PostgreSQL database dump
--

-- Dumped from database version 16.9
-- Dumped by pg_dump version 16.9

-- Started on 2025-09-01 20:35:44

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- TOC entry 907 (class 1247 OID 17222)
-- Name: jenis_peminjaman; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.jenis_peminjaman AS ENUM (
    'Internal',
    'Eksternal'
);


ALTER TYPE public.jenis_peminjaman OWNER TO postgres;

--
-- TOC entry 871 (class 1247 OID 16520)
-- Name: kondisi_barang; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.kondisi_barang AS ENUM (
    'Baik',
    'Rusak',
    'Habis'
);


ALTER TYPE public.kondisi_barang OWNER TO postgres;

--
-- TOC entry 877 (class 1247 OID 16674)
-- Name: status_barang; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_barang AS ENUM (
    'Menunggu Validasi',
    'Tersedia',
    'Dipinjam',
    'Dalam Perbaikan',
    'Rusak Berat',
    'Tidak Aktif'
);


ALTER TYPE public.status_barang OWNER TO postgres;

--
-- TOC entry 874 (class 1247 OID 16528)
-- Name: status_peminjaman; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_peminjaman AS ENUM (
    'Menunggu Validasi',
    'Disetujui',
    'Ditolak',
    'Selesai'
);


ALTER TYPE public.status_peminjaman OWNER TO postgres;

--
-- TOC entry 865 (class 1247 OID 16502)
-- Name: status_pengadaan; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_pengadaan AS ENUM (
    'Validasi',
    'Disetujui',
    'Ditolak'
);


ALTER TYPE public.status_pengadaan OWNER TO postgres;

--
-- TOC entry 868 (class 1247 OID 16510)
-- Name: status_rencana; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_rencana AS ENUM (
    'Diajukan',
    'Validasi Penatausahaan',
    'Disetujui Kepala Dinas',
    'Ditolak'
);


ALTER TYPE public.status_rencana OWNER TO postgres;

--
-- TOC entry 880 (class 1247 OID 16686)
-- Name: status_transaksi; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_transaksi AS ENUM (
    'Diajukan',
    'Divalidasi Pengurus Barang',
    'Divalidasi Penatausahaan',
    'Disetujui Kepala Dinas',
    'Selesai',
    'Ditolak',
    'Menunggu Persetujuan'
);


ALTER TYPE public.status_transaksi OWNER TO postgres;

--
-- TOC entry 862 (class 1247 OID 16472)
-- Name: status_validasi; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.status_validasi AS ENUM (
    'Menunggu',
    'Disetujui',
    'Ditolak'
);


ALTER TYPE public.status_validasi OWNER TO postgres;

--
-- TOC entry 859 (class 1247 OID 16437)
-- Name: user_role; Type: TYPE; Schema: public; Owner: postgres
--

CREATE TYPE public.user_role AS ENUM (
    'Pengurus Barang',
    'Penata Usaha Barang',
    'PPK',
    'Kepala Bidang',
    'Kepala Dinas',
    'Admin'
);


ALTER TYPE public.user_role OWNER TO postgres;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 17045)
-- Name: barang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.barang (
    id integer NOT NULL,
    nama_barang character varying(255) NOT NULL,
    kode_barang character varying(100) NOT NULL,
    kategori_id integer,
    lokasi_id integer,
    merk character varying(100),
    tipe character varying(100),
    spesifikasi text,
    foto_url text,
    tanggal_perolehan date NOT NULL,
    nilai_perolehan numeric(18,2) NOT NULL,
    sumber_dana character varying(100),
    status public.status_barang DEFAULT 'Tersedia'::public.status_barang NOT NULL,
    qr_code_url text,
    pemegang_barang_id integer,
    created_at timestamp with time zone DEFAULT now(),
    updated_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.barang OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 17044)
-- Name: barang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.barang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.barang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 216 (class 1259 OID 17027)
-- Name: kategori_barang; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.kategori_barang (
    id integer NOT NULL,
    nama_kategori character varying(100) NOT NULL,
    kode_kategori character varying(20) NOT NULL
);


ALTER TABLE public.kategori_barang OWNER TO postgres;

--
-- TOC entry 215 (class 1259 OID 17026)
-- Name: kategori_barang_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.kategori_barang ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.kategori_barang_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 230 (class 1259 OID 17102)
-- Name: log_validasi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.log_validasi (
    id integer NOT NULL,
    rencana_pengadaan_id integer,
    peminjaman_id integer,
    penghapusan_id integer,
    user_validator_id integer NOT NULL,
    waktu_validasi timestamp with time zone DEFAULT now(),
    status_sebelum text,
    status_sesudah text,
    catatan text,
    barang_id integer
);


ALTER TABLE public.log_validasi OWNER TO postgres;

--
-- TOC entry 229 (class 1259 OID 17101)
-- Name: log_validasi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.log_validasi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.log_validasi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 218 (class 1259 OID 17037)
-- Name: lokasi; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.lokasi (
    id integer NOT NULL,
    nama_lokasi character varying(100) NOT NULL,
    provinsi character varying(100),
    kab_kota character varying(100),
    kecamatan character varying(100),
    kelurahan_desa character varying(100),
    deskripsi text
);


ALTER TABLE public.lokasi OWNER TO postgres;

--
-- TOC entry 217 (class 1259 OID 17036)
-- Name: lokasi_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.lokasi ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lokasi_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 226 (class 1259 OID 17080)
-- Name: peminjaman; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.peminjaman (
    id integer NOT NULL,
    user_peminjam_id integer NOT NULL,
    tanggal_pengajuan date DEFAULT now() NOT NULL,
    tanggal_mulai_pinjam date NOT NULL,
    tanggal_rencana_kembali date NOT NULL,
    tanggal_aktual_kembali date,
    keperluan text,
    status public.status_transaksi DEFAULT 'Diajukan'::public.status_transaksi NOT NULL,
    catatan_penolakan text,
    created_at timestamp with time zone DEFAULT now(),
    jenis public.jenis_peminjaman DEFAULT 'Internal'::public.jenis_peminjaman NOT NULL,
    nama_pihak_kedua character varying(100),
    nip_pihak_kedua character varying(18),
    jabatan_pihak_kedua character varying(100),
    validator_pengurus_barang_id integer,
    surat_peminjaman_url text,
    nomor_usulan character varying(100) NOT NULL
);


ALTER TABLE public.peminjaman OWNER TO postgres;

--
-- TOC entry 234 (class 1259 OID 17258)
-- Name: peminjaman_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.peminjaman_detail (
    id integer NOT NULL,
    peminjaman_id integer NOT NULL,
    barang_id integer NOT NULL
);


ALTER TABLE public.peminjaman_detail OWNER TO postgres;

--
-- TOC entry 233 (class 1259 OID 17257)
-- Name: peminjaman_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.peminjaman_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peminjaman_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 225 (class 1259 OID 17079)
-- Name: peminjaman_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.peminjaman ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.peminjaman_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 228 (class 1259 OID 17091)
-- Name: penghapusan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.penghapusan (
    id integer NOT NULL,
    barang_id integer NOT NULL,
    user_pengusul_id integer NOT NULL,
    tanggal_pengajuan date DEFAULT now() NOT NULL,
    alasan_penghapusan text NOT NULL,
    status public.status_transaksi DEFAULT 'Diajukan'::public.status_transaksi NOT NULL,
    catatan_penolakan text,
    created_at timestamp with time zone DEFAULT now(),
    foto_kerusakan_url text,
    nomor_usulan character varying(100) NOT NULL,
    berita_acara_url text
);


ALTER TABLE public.penghapusan OWNER TO postgres;

--
-- TOC entry 227 (class 1259 OID 17090)
-- Name: penghapusan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.penghapusan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.penghapusan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 17058)
-- Name: rencana_pengadaan; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rencana_pengadaan (
    id integer NOT NULL,
    nomor_usulan character varying(100) NOT NULL,
    tanggal_usulan date DEFAULT now() NOT NULL,
    program text NOT NULL,
    kegiatan text NOT NULL,
    output text NOT NULL,
    rekening_belanja character varying(255),
    ppk_id integer,
    user_pengusul_id integer NOT NULL,
    status public.status_transaksi DEFAULT 'Diajukan'::public.status_transaksi NOT NULL,
    catatan_penolakan text,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.rencana_pengadaan OWNER TO postgres;

--
-- TOC entry 4988 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN rencana_pengadaan.ppk_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.rencana_pengadaan.ppk_id IS 'FK ke tabel users, menunjuk ke user dengan role PPK';


--
-- TOC entry 4989 (class 0 OID 0)
-- Dependencies: 222
-- Name: COLUMN rencana_pengadaan.user_pengusul_id; Type: COMMENT; Schema: public; Owner: postgres
--

COMMENT ON COLUMN public.rencana_pengadaan.user_pengusul_id IS 'Pengguna yang menginput (Pengurus Barang)';


--
-- TOC entry 224 (class 1259 OID 17071)
-- Name: rencana_pengadaan_detail; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.rencana_pengadaan_detail (
    id integer NOT NULL,
    rencana_id integer NOT NULL,
    nama_barang_usulan character varying(255) NOT NULL,
    jumlah integer NOT NULL,
    satuan character varying(50) NOT NULL,
    harga_satuan numeric(18,2) NOT NULL,
    spesifikasi_usulan text,
    jenis_belanja character varying(100) DEFAULT 'Belanja Modal'::character varying,
    disetujui boolean
);


ALTER TABLE public.rencana_pengadaan_detail OWNER TO postgres;

--
-- TOC entry 223 (class 1259 OID 17070)
-- Name: rencana_pengadaan_detail_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rencana_pengadaan_detail ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rencana_pengadaan_detail_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 221 (class 1259 OID 17057)
-- Name: rencana_pengadaan_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.rencana_pengadaan ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.rencana_pengadaan_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 232 (class 1259 OID 17207)
-- Name: users; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(50) NOT NULL,
    password text NOT NULL,
    nama character varying(100) NOT NULL,
    nip character varying(18),
    jabatan character varying(100),
    role public.user_role NOT NULL,
    created_at timestamp with time zone DEFAULT now()
);


ALTER TABLE public.users OWNER TO postgres;

--
-- TOC entry 231 (class 1259 OID 17206)
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4785 (class 2606 OID 17056)
-- Name: barang barang_kode_barang_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barang
    ADD CONSTRAINT barang_kode_barang_key UNIQUE (kode_barang);


--
-- TOC entry 4787 (class 2606 OID 17054)
-- Name: barang barang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barang
    ADD CONSTRAINT barang_pkey PRIMARY KEY (id);


--
-- TOC entry 4777 (class 2606 OID 17035)
-- Name: kategori_barang kategori_barang_kode_kategori_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kategori_barang
    ADD CONSTRAINT kategori_barang_kode_kategori_key UNIQUE (kode_kategori);


--
-- TOC entry 4779 (class 2606 OID 17033)
-- Name: kategori_barang kategori_barang_nama_kategori_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kategori_barang
    ADD CONSTRAINT kategori_barang_nama_kategori_key UNIQUE (nama_kategori);


--
-- TOC entry 4781 (class 2606 OID 17031)
-- Name: kategori_barang kategori_barang_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.kategori_barang
    ADD CONSTRAINT kategori_barang_pkey PRIMARY KEY (id);


--
-- TOC entry 4803 (class 2606 OID 17109)
-- Name: log_validasi log_validasi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_validasi
    ADD CONSTRAINT log_validasi_pkey PRIMARY KEY (id);


--
-- TOC entry 4783 (class 2606 OID 17043)
-- Name: lokasi lokasi_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.lokasi
    ADD CONSTRAINT lokasi_pkey PRIMARY KEY (id);


--
-- TOC entry 4809 (class 2606 OID 17262)
-- Name: peminjaman_detail peminjaman_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peminjaman_detail
    ADD CONSTRAINT peminjaman_detail_pkey PRIMARY KEY (id);


--
-- TOC entry 4795 (class 2606 OID 17253)
-- Name: peminjaman peminjaman_nomor_usulan_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peminjaman
    ADD CONSTRAINT peminjaman_nomor_usulan_unique UNIQUE (nomor_usulan);


--
-- TOC entry 4797 (class 2606 OID 17089)
-- Name: peminjaman peminjaman_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peminjaman
    ADD CONSTRAINT peminjaman_pkey PRIMARY KEY (id);


--
-- TOC entry 4799 (class 2606 OID 17255)
-- Name: penghapusan penghapusan_nomor_usulan_unique; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.penghapusan
    ADD CONSTRAINT penghapusan_nomor_usulan_unique UNIQUE (nomor_usulan);


--
-- TOC entry 4801 (class 2606 OID 17100)
-- Name: penghapusan penghapusan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.penghapusan
    ADD CONSTRAINT penghapusan_pkey PRIMARY KEY (id);


--
-- TOC entry 4793 (class 2606 OID 17078)
-- Name: rencana_pengadaan_detail rencana_pengadaan_detail_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rencana_pengadaan_detail
    ADD CONSTRAINT rencana_pengadaan_detail_pkey PRIMARY KEY (id);


--
-- TOC entry 4789 (class 2606 OID 17069)
-- Name: rencana_pengadaan rencana_pengadaan_nomor_usulan_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rencana_pengadaan
    ADD CONSTRAINT rencana_pengadaan_nomor_usulan_key UNIQUE (nomor_usulan);


--
-- TOC entry 4791 (class 2606 OID 17067)
-- Name: rencana_pengadaan rencana_pengadaan_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rencana_pengadaan
    ADD CONSTRAINT rencana_pengadaan_pkey PRIMARY KEY (id);


--
-- TOC entry 4805 (class 2606 OID 17214)
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- TOC entry 4807 (class 2606 OID 17216)
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- TOC entry 4810 (class 2606 OID 17110)
-- Name: barang barang_kategori_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barang
    ADD CONSTRAINT barang_kategori_id_fkey FOREIGN KEY (kategori_id) REFERENCES public.kategori_barang(id) ON DELETE SET NULL;


--
-- TOC entry 4811 (class 2606 OID 17115)
-- Name: barang barang_lokasi_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.barang
    ADD CONSTRAINT barang_lokasi_id_fkey FOREIGN KEY (lokasi_id) REFERENCES public.lokasi(id) ON DELETE SET NULL;


--
-- TOC entry 4818 (class 2606 OID 17268)
-- Name: peminjaman_detail fk_barang; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peminjaman_detail
    ADD CONSTRAINT fk_barang FOREIGN KEY (barang_id) REFERENCES public.barang(id);


--
-- TOC entry 4814 (class 2606 OID 17190)
-- Name: log_validasi fk_log_barang; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_validasi
    ADD CONSTRAINT fk_log_barang FOREIGN KEY (barang_id) REFERENCES public.barang(id) ON DELETE CASCADE;


--
-- TOC entry 4819 (class 2606 OID 17263)
-- Name: peminjaman_detail fk_peminjaman; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.peminjaman_detail
    ADD CONSTRAINT fk_peminjaman FOREIGN KEY (peminjaman_id) REFERENCES public.peminjaman(id) ON DELETE CASCADE;


--
-- TOC entry 4815 (class 2606 OID 17166)
-- Name: log_validasi log_validasi_peminjaman_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_validasi
    ADD CONSTRAINT log_validasi_peminjaman_id_fkey FOREIGN KEY (peminjaman_id) REFERENCES public.peminjaman(id) ON DELETE CASCADE;


--
-- TOC entry 4816 (class 2606 OID 17171)
-- Name: log_validasi log_validasi_penghapusan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_validasi
    ADD CONSTRAINT log_validasi_penghapusan_id_fkey FOREIGN KEY (penghapusan_id) REFERENCES public.penghapusan(id) ON DELETE CASCADE;


--
-- TOC entry 4817 (class 2606 OID 17161)
-- Name: log_validasi log_validasi_rencana_pengadaan_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.log_validasi
    ADD CONSTRAINT log_validasi_rencana_pengadaan_id_fkey FOREIGN KEY (rencana_pengadaan_id) REFERENCES public.rencana_pengadaan(id) ON DELETE CASCADE;


--
-- TOC entry 4813 (class 2606 OID 17151)
-- Name: penghapusan penghapusan_barang_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.penghapusan
    ADD CONSTRAINT penghapusan_barang_id_fkey FOREIGN KEY (barang_id) REFERENCES public.barang(id);


--
-- TOC entry 4812 (class 2606 OID 17136)
-- Name: rencana_pengadaan_detail rencana_pengadaan_detail_rencana_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.rencana_pengadaan_detail
    ADD CONSTRAINT rencana_pengadaan_detail_rencana_id_fkey FOREIGN KEY (rencana_id) REFERENCES public.rencana_pengadaan(id) ON DELETE CASCADE;


-- Completed on 2025-09-01 20:35:44

--
-- PostgreSQL database dump complete
--

