CREATE TYPE "user_role" AS ENUM (
  'Pengurus Barang',
  'Penata Usaha Barang',
  'PPK',
  'Kepala Bidang',
  'Kepala Dinas',
  'Admin'
);

CREATE TYPE "status_barang" AS ENUM (
  'Menunggu Validasi',  --new
  'Tersedia',
  'Dipinjam',
  'Dalam Perbaikan',
  'Rusak Berat',
  'Tidak Aktif'
);

CREATE TYPE "status_transaksi" AS ENUM (
  'Diajukan',
  'Divalidasi Pengurus Barang',
  'Divalidasi Penatausahaan',
  'Disetujui Kepala Dinas',
  'Selesai',
  'Ditolak'
);

CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(50) UNIQUE NOT NULL,
  "password" text NOT NULL,
  "nama" varchar(100) NOT NULL,
  "nip" varchar(18), 
  "jabatan" varchar(100), 
  "role" user_role NOT NULL,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "kategori_barang" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_kategori" varchar(100) UNIQUE NOT NULL,
  "kode_kategori" varchar(20) UNIQUE NOT NULL
);

CREATE TABLE "lokasi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_lokasi" varchar(100) NOT NULL,
  "provinsi" varchar(100),
  "kab_kota" varchar(100),
  "kecamatan" varchar(100),
  "kelurahan_desa" varchar(100),
  "deskripsi" text
);

CREATE TABLE "barang" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nama_barang" varchar(255) NOT NULL,
  "kode_barang" varchar(100) UNIQUE NOT NULL,
  "kategori_id" int,
  "lokasi_id" int,
  "merk" varchar(100),
  "tipe" varchar(100),
  "spesifikasi" text,
  "foto_url" text,
  "tanggal_perolehan" date NOT NULL,
  "nilai_perolehan" decimal(18,2) NOT NULL,
  "sumber_dana" varchar(100),
  "status" status_barang NOT NULL DEFAULT 'Tersedia',
  "qr_code_url" text,
  "pemegang_barang_id" int,
  "created_at" timestamptz DEFAULT (now()),
  "updated_at" timestamptz DEFAULT (now())
);

CREATE TABLE "rencana_pengadaan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "nomor_usulan" varchar(100) UNIQUE NOT NULL,
  "tanggal_usulan" date NOT NULL DEFAULT (now()),
  "program" text NOT NULL,
  "kegiatan" text NOT NULL,
  "output" text NOT NULL,
  "rekening_belanja" varchar(255),
  "ppk_id" int,
  "user_pengusul_id" int NOT NULL,
  "status" status_transaksi NOT NULL DEFAULT 'Diajukan',
  "catatan_penolakan" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "rencana_pengadaan_detail" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rencana_id" int NOT NULL,
  "nama_barang_usulan" varchar(255) NOT NULL,
  "jumlah" int NOT NULL,
  "satuan" varchar(50) NOT NULL,
  "harga_satuan" decimal(18,2) NOT NULL,
  "spesifikasi_usulan" text,
  "jenis_belanja" varchar(100) DEFAULT 'Belanja Modal'
);

CREATE TABLE "peminjaman" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barang_id" int NOT NULL,
  "user_peminjam_id" int NOT NULL,
  "tanggal_pengajuan" date NOT NULL DEFAULT (now()),
  "tanggal_mulai_pinjam" date NOT NULL,
  "tanggal_rencana_kembali" date NOT NULL,
  "tanggal_aktual_kembali" date,
  "keperluan" text,
  "status" status_transaksi NOT NULL DEFAULT 'Diajukan',
  "catatan_penolakan" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "penghapusan" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "barang_id" int NOT NULL,
  "user_pengusul_id" int NOT NULL,
  "tanggal_pengajuan" date NOT NULL DEFAULT (now()),
  "alasan_penghapusan" text NOT NULL,
  "status" status_transaksi NOT NULL DEFAULT 'Diajukan',
  "catatan_penolakan" text,
  "created_at" timestamptz DEFAULT (now())
);

CREATE TABLE "log_validasi" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "rencana_pengadaan_id" int,
  "peminjaman_id" int,
  "penghapusan_id" int,
  "user_validator_id" int NOT NULL,
  "waktu_validasi" timestamptz DEFAULT (now()),
  "status_sebelum" status_transaksi,
  "status_sesudah" status_transaksi,
  "catatan" text
);

COMMENT ON COLUMN "rencana_pengadaan"."ppk_id" IS 'FK ke tabel users, menunjuk ke user dengan role PPK';

COMMENT ON COLUMN "rencana_pengadaan"."user_pengusul_id" IS 'Pengguna yang menginput (Pengurus Barang)';

ALTER TABLE "barang" ADD FOREIGN KEY ("kategori_id") REFERENCES "kategori_barang" ("id") ON DELETE SET NULL;

ALTER TABLE "barang" ADD FOREIGN KEY ("lokasi_id") REFERENCES "lokasi" ("id") ON DELETE SET NULL;

ALTER TABLE "barang" ADD FOREIGN KEY ("pemegang_barang_id") REFERENCES "users" ("id") ON DELETE SET NULL;

ALTER TABLE "rencana_pengadaan" ADD FOREIGN KEY ("ppk_id") REFERENCES "users" ("id");

ALTER TABLE "rencana_pengadaan" ADD FOREIGN KEY ("user_pengusul_id") REFERENCES "users" ("id");

ALTER TABLE "rencana_pengadaan_detail" ADD FOREIGN KEY ("rencana_id") REFERENCES "rencana_pengadaan" ("id") ON DELETE CASCADE;

ALTER TABLE "peminjaman" ADD FOREIGN KEY ("barang_id") REFERENCES "barang" ("id");

ALTER TABLE "peminjaman" ADD FOREIGN KEY ("user_peminjam_id") REFERENCES "users" ("id");

ALTER TABLE "penghapusan" ADD FOREIGN KEY ("barang_id") REFERENCES "barang" ("id");

ALTER TABLE "penghapusan" ADD FOREIGN KEY ("user_pengusul_id") REFERENCES "users" ("id");

ALTER TABLE "log_validasi" ADD FOREIGN KEY ("rencana_pengadaan_id") REFERENCES "rencana_pengadaan" ("id") ON DELETE CASCADE;

ALTER TABLE "log_validasi" ADD FOREIGN KEY ("peminjaman_id") REFERENCES "peminjaman" ("id") ON DELETE CASCADE;

ALTER TABLE "log_validasi" ADD FOREIGN KEY ("penghapusan_id") REFERENCES "penghapusan" ("id") ON DELETE CASCADE;

ALTER TABLE "log_validasi" ADD FOREIGN KEY ("user_validator_id") REFERENCES "users" ("id");
